services:
  - type: worker
    name: classplus-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.telegram_bot
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.15
      - key: TELEGRAM_BOT_TOKEN
        sync: false